config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'navigations#album'
  get '/album',      to: 'navigations#album',       as: :album
  get '/exit',       to: 'navigation#exit',         as: :exit
  get '/stickers',   to: 'navigations#stickers',    as: :stickers
  get '/packs',      to: 'navigations#packs',       as: :packs
  get '/new-trade',  to: 'navigations#new_trade',   as: :new_trade
  get '/trades',     to: 'navigations#trade',       as: :trade_requests

  resources :users, only: [:index] do
  	resources :albums, only: [:show] do
  		resources :spots, only: [:new,:create]
  	end
    resources :stickers,       only: [:index]
    get '/search',             to: 'stickers#search'
    resources :sticker_packs,  only: [:index, :update]
    resources :trade_requests, only: [:index, :create, :update]  
  end
end

app/models/trade_request.rb
class TradeRequest < ApplicationRecord
	belongs_to :offerer,  class_name:'User', 
	                      foreign_key: 'offerer_id',
	                      inverse_of: :trade_request_offered
	belongs_to :receiver, class_name:'User', 
	                      foreign_key: 'receiver_id', 
	                      inverse_of: :trade_request_received
	enum response: [:not_responsed, :denied, :acepted]

	after_create :send_trade_request_mailer_to_receiver
	after_update :send_trade_request_mailer_to_offerer

	before_update :set_responsed_at

	def send_trade_request_mailer_to_receiver
		TradeRequestMailer.with(trade_request: self)
						  .notify_receiver.deliver_later
	end

	def send_trade_request_mailer_to_offerer
		TradeRequestMailer.with(trade_request_id: self.id)
			.notify_offerer.deliver_later if request_responsed?
								
	end

	def set_responsed_at
		self.responsed_at = Time.now unless request_responsed?
	end

	private
		def request_responsed?
			!self.not_responsed? && self.responsed_at.present?
		end
end

app/controllers/trade_requests_controller.rb
class TradeRequestsController < ApplicationController
	def index
		@user = current_user

		@trade_requests = @user.trade_requests
			.paginate(page: params[:page], per_page: 10)
						
		@trade_request_to_responses = 
			@user.trade_request_to_responses
				 .paginate(page: params[:page], per_page: 10)
	end

	def create
		@offerer = current_user
		username = permitted_params[:username]

		if(User.exists?(username: username))
			@receiver = 
				User.find_by_username(permitted_params[:username])
			    @trade_request = 
			    	@offerer.trade_request_offered
			    	        .build(receiver_id: @receiver.id)
			    if(username == @offerer.username)
			    	flash[:alert] = t('sticker_album.trade_request.yourself')
			    	redirect_to new_trade_path
			    end 

			    if(@trade_request.save!)
			    	flash[:notice] = 
			    		t('sticker_album.trade_request.successfull')
			    else
			    	flash[:alert] = t('sticker_album.trade_request.error')
			    end
		else
			flash[:alert] = 
				t('sticker_album.trade_request.error_username')
				+" Username: #{username}"
		end
		flash[:notice] = t('sticker_album.trade_request.successfull')
		redirect_to new_trade_path
	end

	def update
		@trade_request_id = permitted_params[:id]
		@trade_request = TradeRequest.find(@trade_request_id)
		@trade_request.response = permitted_params[:response].to_i
		@trade_request.save
		redirect_to trade_requests_path
	end

	private
		def permitted_params
			params.permit(:id,:user_id,:username,:response)
		end
end

app/helpers/trade_request_helper.rb
module TradeRequestHelper 
	def render_trade_history_response_type trade_request
		if trade_request.not_responsed?
			classify = "active"
		elsif trade_request.denied?
			classify = "danger"
		else trade_request.acepted?
			classify = "success"
		end
		classify
	end
end

app/views/trade_requests/_form.html.erb
<!-- Send Trade Request -->
<%= link_to t('sticker_album.trade_request.new'), 
				"/users/#{user.id}/trade_requests"+
				"?username=#{user.username}",
				method: :post, 
				class:"btn btn-info",
				remote: true %>  

app/views/trade_requests/_to_response.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<caption><h4><%= t('sticker_album.trade_request.to_response.title') %></h4></caption>
				<tr>
					<th><%= t('sticker_album.trade_request.to_response.offerer') %></th>
					<th><%= t('sticker_album.trade_request.to_response.reponse') %></th>
				</tr>
				<% @trade_request_to_responses.each do |trade_request_to_response| %>
					<tr id=<%="#{trade_request_to_response.id}"%> >
						<td> 
							<% username = trade_request_to_response.offerer.username %>
							<% trade_id = trade_request_to_response.id %>
							<%= link_to username, 
										"#{user_search_path(current_user)}"+
										"?username=#{username}", 
										class:"btn btn-link",
										'data-toggle'=>"modal",
										'data-target'=>"#application-modal",
										remote: true %>
						</td>
						<td>
							<%= link_to t('sticker_album.trade_request.deny'), 
										"#{user_trade_request_path(current_user,trade_request_to_response)}"+
										"?response=1",
										method: :patch, 
										class:"btn btn-danger",
										remote: true %>
							<%= link_to t('sticker_album.trade_request.acept'), 
										"#{user_trade_request_path(current_user,trade_request_to_response)}"+
										"?response=2",
										method: :patch, 
										class:"btn btn-success",
										remote: true %>
						</td>
					</tr>
				<%end%>
				<tr><td colspan=2><%= render inline: t('sticker_album.nothing') if @trade_request_to_responses%></td></tr>
			</table>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= will_paginate @trade_request_to_responses, renderer: BootstrapPagination::Rails %>
	</div>
</div>

app/views/trade_requests/_trade_history.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table class="table table-bordered">
				<caption><h4><%= t('sticker_album.trade_request.history.title') %></h4></caption>
				<tr>
					<th><%= t('sticker_album.trade_request.history.date')         %></th>
					<th><%= t('sticker_album.trade_request.history.offerer')      %></th>
					<th><%= t('sticker_album.trade_request.history.receiver')     %></th>
					<th><%= t('sticker_album.trade_request.history.response')     %></th>
					<th><%= t('sticker_album.trade_request.history.response_date')%></th>
				</tr>
				<%= render @trade_requests || t('sticker_album.nothing') %>
			</table>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= will_paginate @trade_requests, renderer: BootstrapPagination::Rails %>
	</div>
</div>

app/views/trade_requests/_trade_request.html.erb
<tr class="<%= render_trade_history_response_type(trade_request) %>"> 
	<td><%= trade_request.created_at.strftime("%d %b %Y %H:%M") if trade_request.responsed_at%>    </td>
	<td><%= trade_request.offerer.username %>  </td>
	<td><%= trade_request.receiver.username %> </td>
	<td><%= trade_request.response.titleize %>          </td>
	<td><%= trade_request.responsed_at.strftime("%d %b %Y %H:%M") if trade_request.responsed_at %> </td>
</tr>

app/views/trade_requests/index.html.erb
<%= render "to_response" %>
<%= render "trade_history" %>

app/views/trade_requests/notify_receiver.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Hello&nbsp;<%= @receiver.username %>,</h1>
    <p>
      My username is <%= @fferer.username %> 
      I would like trade my Stickers with you.<br>
    </p>
    <!-- <p>
      Take a look at them here &nbsp;<%= @url %>.
    </p> -->
    <p>Thanks!</p>
  </body>
</html>