config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'navigations#album'
  get '/album',      to: 'navigations#album',       as: :album
  get '/exit',       to: 'navigation#exit',         as: :exit
  get '/stickers',   to: 'navigations#stickers',    as: :stickers
  get '/packs',      to: 'navigations#packs',       as: :packs
  get '/new-trade',  to: 'navigations#new_trade',   as: :new_trade
  get '/trades',     to: 'navigations#trade',       as: :trade_requests

  resources :users, only: [:index] do
  	resources :albums, only: [:show] do
  		resources :spots, only: [:new,:create]
  	end
    resources :stickers,       only: [:index]
    get '/search',             to: 'stickers#search'
    resources :sticker_packs,  only: [:index, :update]
    resources :trade_requests, only: [:index, :create, :update]  
  end
end

app/views/layouts/_messages.html.erb
<div class="messages">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>
</div>

app/views/layouts/_modal.html.erb
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="application-modal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel"><%= application_modal_title_helper %></h4>
      </div>
      <div class="modal-body">
        
          <div id="modal-application-content">

          </div>          
         
      </div>
      <div class="modal-footer">
        <%= render_application_modal_footer_content_form %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default bg-primary navbar-fixed-top" role="navigation">
    <div class="container">
    <div class="navbar-header navbar-right">
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <li> <%= exit_helper %></li>
        </ul>
      </div>
    </div>
    <div class="navbar-header navbar-right">
      <a class="navbar-brand" href="#">
        <%= wellcome_helper %>
      </a>
      <button type="button" data-target="#menu-collapse" data-toggle="collapse" class="navbar-toggle pull-rigth">
        <span class="sr-only"> </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="menu-collapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-left" id="top-nav">
          <li><%= link_active_helper t('sticker_album.navigation.album'),         album_path           %></li>
          <li><%= link_active_helper t('sticker_album.navigation.stickers'),      stickers_path          %></li>
          <li><%= link_active_helper t('sticker_album.navigation.packs'),         packs_path            %></li>
          <li><%= link_active_helper t('sticker_album.navigation.new_trades'),    new_trade_path       %></li>
          <li><%= link_active_helper t('sticker_album.navigation.trade_history'), trade_requests_path   %></li>
        </ul>
    </div>     
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StickerAlbum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render "layouts/navigation" if user_signed_in? %>
    <%= render "layouts/modal" if user_signed_in? %>
    <%= render "layouts/messages" %>

    <section id="section-main"> 
      <div class="container">
        <% if user_signed_in? %>
          <%= yield %>
        <% else %>
          <div class="row">
            <div class="col-md-4 col-md-offset-3">
              <%= yield %>
            </div>
          </div>
        <% end %>
      </div>
    </section>
  </body>
</html>